image: python:2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"


robot-tests:
  script:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
  - cd src/dc-wordpress/tests; PYTHONPATH=$PYTHONPATH:$(pwd) robot http.robot
