---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: game-ingress
spec:
  rules:
  - host: game.domain1.io
    http:
      paths:
      - path:
        backend:
          serviceName: game2048
          servicePort: 80
<<<<<<< HEAD
=======


>>>>>>> f70e1efe176e6acbb18314916e78c84d0f92a854
